-- =============================================================
-- init_postgres.sql
-- Schema completo del sistema Clauman para PostgreSQL.
-- Ejecutar UNA VEZ contra una base recién creada en Neon/Render/Supabase.
--
-- Diferencias vs SQL Server:
--   - identidades con GENERATED BY DEFAULT AS IDENTITY (no IDENTITY(1,1))
--   - tipos: NVARCHAR → VARCHAR, BIT → BOOLEAN
--   - timestamps: DATETIME → TIMESTAMP
--   - usamos lowercase para nombres de tabla y columna por convención Postgres
--     (igual el código C# usa Pascal Case en los identifiers SQL, pero Postgres
--     baja a minúsculas si no van entre comillas — funciona transparente)
-- =============================================================

-- ============ MANTENEDORES ============

CREATE TABLE IF NOT EXISTS Categorias (
    Id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Clientes (
    Id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rut       VARCHAR(20)  NOT NULL,
    Nombre    VARCHAR(200) NOT NULL,
    Direccion VARCHAR(200) NOT NULL DEFAULT '',
    Comuna    VARCHAR(100) NOT NULL DEFAULT '',
    Ciudad    VARCHAR(100) NOT NULL DEFAULT '',
    Giro      VARCHAR(200) NOT NULL DEFAULT '',
    Telefono  VARCHAR(50)  NOT NULL DEFAULT '',
    EmailCorp VARCHAR(150) NOT NULL DEFAULT '',
    EmailCot  VARCHAR(150) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Proveedores (
    Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rut         VARCHAR(20)  NOT NULL,
    RazonSocial VARCHAR(200) NOT NULL,
    Direccion   VARCHAR(200) NOT NULL DEFAULT '',
    Ciudad      VARCHAR(100) NOT NULL DEFAULT '',
    Telefono    VARCHAR(50)  NOT NULL DEFAULT '',
    EmailCorp   VARCHAR(150) NOT NULL DEFAULT '',
    Ejecutivo   VARCHAR(150) NOT NULL DEFAULT '',
    EmailCot    VARCHAR(150) NOT NULL DEFAULT '',
    Banco       VARCHAR(100) NOT NULL DEFAULT '',
    CtaCte      VARCHAR(50)  NOT NULL DEFAULT '',
    RutTitular  VARCHAR(20)  NOT NULL DEFAULT '',
    EmailPagos  VARCHAR(150) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Inventario (
    Id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Codigo          VARCHAR(50),
    Descripcion     VARCHAR(200),
    CategoriaId     INT REFERENCES Categorias(Id),
    Ubicacion       VARCHAR(100),
    StockVina       INT DEFAULT 0,
    StockVa         INT DEFAULT 0,
    PrecioMeson     INT DEFAULT 0,
    PrecioMayor     INT DEFAULT 0,
    PrecioWeb       INT DEFAULT 0,
    CostoNeto       INT DEFAULT 0,
    Utilidad        INT DEFAULT 0,
    TieneImagen     BOOLEAN DEFAULT FALSE,
    Observacion     VARCHAR(500),
    Compatibilidad  VARCHAR(500)
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Inventario_Codigo ON Inventario(Codigo);

-- ============ USUARIOS / AUTH ============

CREATE TABLE IF NOT EXISTS Usuarios (
    Id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rut          VARCHAR(20),
    Nombre       VARCHAR(100) NOT NULL,
    Username     VARCHAR(50)  NOT NULL UNIQUE,
    PasswordHash VARCHAR(200) NOT NULL,
    Rol          VARCHAR(20)  NOT NULL DEFAULT 'CAJERO',
    Activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CreadoEn     TIMESTAMP    NOT NULL DEFAULT NOW(),
    Permisos     TEXT
);

CREATE TABLE IF NOT EXISTS AccesosLog (
    Id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UsuarioId INT,
    Username  VARCHAR(50) NOT NULL,
    Fecha     TIMESTAMP NOT NULL DEFAULT NOW(),
    Exito     BOOLEAN NOT NULL DEFAULT FALSE,
    Local     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS SesionTokens (
    Token      VARCHAR(64) PRIMARY KEY,
    UsuarioId  INT NOT NULL REFERENCES Usuarios(Id) ON DELETE CASCADE,
    CreadoEn   TIMESTAMP NOT NULL DEFAULT NOW(),
    ExpiraEn   TIMESTAMP NOT NULL,
    UltimoUso  TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============ TRANSACCIONALES — VENTAS ============

CREATE TABLE IF NOT EXISTS Boletas (
    Id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero     INT NOT NULL,
    Fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora       TIME NOT NULL DEFAULT CURRENT_TIME,
    ClienteId  INT REFERENCES Clientes(Id),
    MedioPago  VARCHAR(30) NOT NULL DEFAULT 'EFECTIVO',
    DescGlobal INT NOT NULL DEFAULT 0,
    TotalNeto  INT NOT NULL DEFAULT 0,
    Iva        INT NOT NULL DEFAULT 0,
    Total      INT NOT NULL DEFAULT 0,
    Usuario    VARCHAR(50) NOT NULL,
    Anulada    BOOLEAN NOT NULL DEFAULT FALSE,
    Bodega     VARCHAR(20) NOT NULL DEFAULT 'VINA'
);

CREATE TABLE IF NOT EXISTS BoletasDetalle (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BoletaId       INT NOT NULL REFERENCES Boletas(Id),
    ProductoId     INT REFERENCES Inventario(Id),
    Codigo         VARCHAR(50) NOT NULL,
    Descripcion    VARCHAR(200) NOT NULL,
    Cantidad       INT NOT NULL,
    PrecioUnitario INT NOT NULL,
    Subtotal       INT GENERATED ALWAYS AS (Cantidad * PrecioUnitario) STORED
);

CREATE TABLE IF NOT EXISTS NotasVenta (
    Id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero     INT NOT NULL,
    Fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora       TIME NOT NULL DEFAULT CURRENT_TIME,
    ClienteId  INT REFERENCES Clientes(Id),
    ClienteRef VARCHAR(200) NOT NULL DEFAULT '',
    CondVenta  VARCHAR(20) NOT NULL DEFAULT 'MESON',
    MedioPago  VARCHAR(30) NOT NULL DEFAULT 'EFECTIVO',
    DescGlobal INT NOT NULL DEFAULT 0,
    TotalNeto  INT NOT NULL DEFAULT 0,
    Iva        INT NOT NULL DEFAULT 0,
    Total      INT NOT NULL DEFAULT 0,
    Estado     VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    Usuario    VARCHAR(50) NOT NULL,
    Bodega     VARCHAR(20) NOT NULL DEFAULT 'VINA'
);

CREATE TABLE IF NOT EXISTS NotasVentaDetalle (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NotaVentaId    INT NOT NULL REFERENCES NotasVenta(Id),
    ProductoId     INT REFERENCES Inventario(Id),
    Codigo         VARCHAR(50) NOT NULL,
    Descripcion    VARCHAR(200) NOT NULL,
    Cantidad       INT NOT NULL,
    PrecioUnitario INT NOT NULL,
    Subtotal       INT GENERATED ALWAYS AS (Cantidad * PrecioUnitario) STORED
);

CREATE TABLE IF NOT EXISTS Cotizaciones (
    Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero      INT NOT NULL,
    Fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora        TIME NOT NULL DEFAULT CURRENT_TIME,
    ClienteId   INT REFERENCES Clientes(Id),
    ClienteRef  VARCHAR(200) NOT NULL DEFAULT '',
    CondVenta   VARCHAR(20) NOT NULL DEFAULT 'MESON',
    DescGlobal  INT NOT NULL DEFAULT 0,
    Total       INT NOT NULL DEFAULT 0,
    Estado      VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    Usuario     VARCHAR(50) NOT NULL,
    Vencimiento DATE
);

CREATE TABLE IF NOT EXISTS CotizacionesDetalle (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CotizacionId   INT NOT NULL REFERENCES Cotizaciones(Id),
    ProductoId     INT REFERENCES Inventario(Id),
    Codigo         VARCHAR(50) NOT NULL,
    Descripcion    VARCHAR(200) NOT NULL,
    Cantidad       INT NOT NULL,
    PrecioUnitario INT NOT NULL,
    Subtotal       INT GENERATED ALWAYS AS (Cantidad * PrecioUnitario) STORED
);

CREATE TABLE IF NOT EXISTS Facturas (
    Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero      INT NOT NULL,
    Folio       INT NOT NULL,
    Fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora        TIME NOT NULL DEFAULT CURRENT_TIME,
    ClienteId   INT NOT NULL REFERENCES Clientes(Id),
    CondVenta   VARCHAR(20) NOT NULL DEFAULT 'CONTADO',
    OrdenCompra VARCHAR(50) NOT NULL DEFAULT '',
    DescGlobal  INT NOT NULL DEFAULT 0,
    TotalNeto   INT NOT NULL DEFAULT 0,
    Iva         INT NOT NULL DEFAULT 0,
    Total       INT NOT NULL DEFAULT 0,
    Estado      VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    Usuario     VARCHAR(50) NOT NULL,
    Vencimiento DATE,
    Bodega      VARCHAR(20) NOT NULL DEFAULT 'VINA'
);

CREATE TABLE IF NOT EXISTS FacturasDetalle (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FacturaId      INT NOT NULL REFERENCES Facturas(Id),
    ProductoId     INT REFERENCES Inventario(Id),
    Codigo         VARCHAR(50) NOT NULL,
    Descripcion    VARCHAR(200) NOT NULL,
    Cantidad       INT NOT NULL,
    PrecioUnitario INT NOT NULL,
    Subtotal       INT GENERATED ALWAYS AS (Cantidad * PrecioUnitario) STORED
);

CREATE TABLE IF NOT EXISTS NotasCredito (
    Id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero          INT NOT NULL,
    Fecha           DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora            TIME NOT NULL DEFAULT CURRENT_TIME,
    TipoDocOrigen   VARCHAR(20) NOT NULL,
    DocOrigenId     INT NOT NULL,
    DocOrigenNumero INT NOT NULL,
    ClienteId       INT REFERENCES Clientes(Id),
    Total           INT NOT NULL DEFAULT 0,
    Motivo          VARCHAR(300) NOT NULL DEFAULT '',
    Usuario         VARCHAR(50) NOT NULL,
    Bodega          VARCHAR(20) NOT NULL DEFAULT 'VINA',
    Anulada         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS NotasCreditoDetalle (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NotaCreditoId  INT NOT NULL REFERENCES NotasCredito(Id),
    ProductoId     INT REFERENCES Inventario(Id),
    Codigo         VARCHAR(50) NOT NULL,
    Descripcion    VARCHAR(200) NOT NULL,
    Cantidad       INT NOT NULL,
    PrecioUnitario INT NOT NULL
);

-- ============ TRASLADOS / COMPRAS ============

CREATE TABLE IF NOT EXISTS Traslados (
    Id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero       INT NOT NULL,
    Fecha        DATE NOT NULL DEFAULT CURRENT_DATE,
    Hora         TIME NOT NULL DEFAULT CURRENT_TIME,
    BodegaOrigen VARCHAR(50) NOT NULL,
    BodegaDest   VARCHAR(50) NOT NULL,
    Estado       VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    Usuario      VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TrasladosDetalle (
    Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TrasladoId  INT NOT NULL REFERENCES Traslados(Id),
    ProductoId  INT REFERENCES Inventario(Id),
    Codigo      VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(200) NOT NULL,
    Cantidad    INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FacturasCompra (
    Id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha          DATE NOT NULL DEFAULT CURRENT_DATE,
    TipoDoc        VARCHAR(20) NOT NULL DEFAULT 'FACTURA',
    NumeroDoc      VARCHAR(50) NOT NULL,
    ProveedorId    INT NOT NULL REFERENCES Proveedores(Id),
    OrdenCompra    VARCHAR(50) NOT NULL DEFAULT '',
    CondVenta      VARCHAR(20) NOT NULL DEFAULT 'CONTADO',
    TotalNeto      INT NOT NULL DEFAULT 0,
    Iva            INT NOT NULL DEFAULT 0,
    Total          INT NOT NULL DEFAULT 0,
    Estado         VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    FechaRecepcion DATE,
    Vencimiento    DATE,
    Usuario        VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FacturasCompraDetalle (
    Id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FacturaCompraId INT NOT NULL REFERENCES FacturasCompra(Id),
    ProductoId      INT REFERENCES Inventario(Id),
    Codigo          VARCHAR(50) NOT NULL,
    Descripcion     VARCHAR(200) NOT NULL,
    Cantidad        INT NOT NULL,
    PrecioNeto      INT NOT NULL,
    PrecioMeson     INT NOT NULL DEFAULT 0,
    PrecioMayor     INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Ajustes (
    Id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha       TIMESTAMP NOT NULL DEFAULT NOW(),
    Local       VARCHAR(20) NOT NULL DEFAULT 'VINA',
    Tipo        VARCHAR(50) NOT NULL DEFAULT 'AJUSTE INVENTARIO',
    ProductoId  INT REFERENCES Inventario(Id),
    Codigo      VARCHAR(50) NOT NULL DEFAULT '',
    Descripcion VARCHAR(200) NOT NULL DEFAULT '',
    Motivo      VARCHAR(300) NOT NULL DEFAULT '',
    Ajuste      INT NOT NULL DEFAULT 0,
    Usuario     VARCHAR(50) NOT NULL
);

-- ============ CONFIG ============

CREATE TABLE IF NOT EXISTS Parametros (
    Clave       VARCHAR(50) PRIMARY KEY,
    Valor       VARCHAR(500) NOT NULL,
    Descripcion VARCHAR(200) NOT NULL DEFAULT ''
);

-- ============ SEEDS ============

-- Categorías base
INSERT INTO Categorias (Nombre) VALUES
    ('ACCESORIO'),('ACEITE'),('BATERIA'),('BODEGA'),('CHEVROLET'),
    ('FILTRO'),('MITSUBISHI'),('MULTIMARCAS'),('PASTILLA'),('SSANGYONG'),
    ('SUZUKI'),('VARIOS')
ON CONFLICT (Nombre) DO NOTHING;

-- Parámetros del sistema
INSERT INTO Parametros (Clave, Valor, Descripcion) VALUES
    ('descuento1',       '0',                                       'Descuento 1 por defecto (%)'),
    ('descuento2',       '0',                                       'Descuento 2 por defecto (%)'),
    ('iva',              '19',                                      'IVA aplicado en ventas (%)'),
    ('empresa_nombre',   'ClauMan SpA',                             'Razón social de la empresa'),
    ('empresa_rut',      '76.123.456-7',                            'RUT de la empresa'),
    ('empresa_giro',     'Comercio de repuestos automotrices',      'Giro comercial'),
    ('empresa_direccion','Av. Principal 1234, Viña del Mar',        'Dirección'),
    ('empresa_telefono', '+56 32 1234567',                          'Teléfono')
ON CONFLICT (Clave) DO NOTHING;

-- Usuario admin inicial — contraseña: CAMBIAR_INMEDIATAMENTE_001!
-- SHA256 verificado de "CAMBIAR_INMEDIATAMENTE_001!"
-- DESPUÉS DEL PRIMER LOGIN: usa el script cambiar_password.ps1 o el modal en la UI para cambiar la contraseña.
INSERT INTO Usuarios (Rut, Nombre, Username, PasswordHash, Rol) VALUES
    ('11.111.111-1', 'Administrador', 'admin',
     '6eb4b988792bcd8227c7836c73a6adf202ce9db71930204be9cf2613663fdefc',
     'ADMIN')
ON CONFLICT (Username) DO NOTHING;
